### ISSUE TITLE
sim-it simulated reads all start at position 0

### ISSUE THREAD

**Issue by sebschmi** [ndierckx/Sim-it#1]
It seems like sim-it does not choose the starting position randomly, but just uses 0 every time. See lines 3180-3188 in Sim-it1.2.pl

**Comment by ndierckx** [comment]
Hi,

If you have for example a coverage of 10, you have indeed 10 reads of different lengths that start (or end) at position 0, which is normal for a linear genome..

I could add an additional option for circular genomes so that some reads overlap both the end and the start of the genome sequence. Is that what you mean?

Greets

**Comment by sebschmi** [comment]
Hi,

thanks for the quick reply. Apparently I do not understand the code correctly. Indeed, only the first few reads start at position 0, and the later ones start at different positions.

I originally thought _every_ read would start at position 0, but that does not seem to be the case.
